/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:22:04 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIKit-Structs.h>
#import <libobjc.A.dylib/NSItemProviderReading.h>
#import <libobjc.A.dylib/NSItemProviderWriting.h>
#import <UIKit/UIItemProviderPresentationSizeProviding.h>
#import <UIKit/UIItemProviderReading.h>
#import <UIKit/UIItemProviderWriting.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSArray, UITraitCollection, _UIImageVectorImageSupport, UIImageAsset, NSString, CIImage, UIGraphicsImageRendererFormat;

@interface UIImage : NSObject <NSItemProviderReading, NSItemProviderWriting, UIItemProviderPresentationSizeProviding, UIItemProviderReading, UIItemProviderWriting, NSSecureCoding> {

	void* _imageRef;
	double _scale;
	struct {
		unsigned named : 1;
		unsigned imageOrientation : 3;
		unsigned cached : 1;
		unsigned hasPattern : 1;
		unsigned isCIImage : 1;
		unsigned renderingMode : 2;
		unsigned suppressesAccessibilityHairlineThickening : 1;
		unsigned hasDecompressionInfo : 1;
	}  _imageFlags;
	BOOL _flipsForRightToLeftLayoutDirection;
	UITraitCollection* _traitCollection;
	_UIImageVectorImageSupport* _vectorImageSupport;
	UIImageAsset* _imageAsset;
	UIEdgeInsets _alignmentRectInsets;

}

@property (nonatomic,readonly) long long leftCapWidth; 
@property (nonatomic,readonly) long long topCapHeight; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy,readonly) NSArray * writableTypeIdentifiersForItemProvider; 
@property (nonatomic,readonly) CGSize preferredPresentationSizeForItemProvider; 
@property (nonatomic,retain) _UIImageVectorImageSupport * vectorImageSupport;                      //@synthesize vectorImageSupport=_vectorImageSupport - In the implementation block
@property (nonatomic,retain) UIImageAsset * imageAsset;                                            //@synthesize imageAsset=_imageAsset - In the implementation block
@property (nonatomic,copy) UITraitCollection * traitCollection;                                    //@synthesize traitCollection=_traitCollection - In the implementation block
@property (getter=_CGPDFPage,nonatomic,readonly) CGPDFPageRef CGPDFPage; 
@property (nonatomic,readonly) CGSize size; 
@property (nonatomic,readonly) CGImageRef CGImage; 
@property (nonatomic,readonly) CIImage * CIImage; 
@property (nonatomic,readonly) long long imageOrientation; 
@property (nonatomic,readonly) double scale; 
@property (nonatomic,readonly) NSArray * images; 
@property (nonatomic,readonly) double duration; 
@property (nonatomic,readonly) UIEdgeInsets capInsets; 
@property (nonatomic,readonly) long long resizingMode; 
@property (nonatomic,readonly) UIEdgeInsets alignmentRectInsets;                                   //@synthesize alignmentRectInsets=_alignmentRectInsets - In the implementation block
@property (nonatomic,readonly) long long renderingMode; 
@property (nonatomic,readonly) UIGraphicsImageRendererFormat * imageRendererFormat; 
@property (nonatomic,readonly) BOOL flipsForRightToLeftLayoutDirection;                            //@synthesize flipsForRightToLeftLayoutDirection=_flipsForRightToLeftLayoutDirection - In the implementation block
+(id)kitImageNamed:(id)arg1 ;
+(void)initialize;
+(void)_flushSharedImageCache;
+(id)_applicationIconImageForBundleIdentifier:(id)arg1 format:(int)arg2 scale:(double)arg3 ;
+(id)_tintedImageForSize:(CGSize)arg1 withTint:(id)arg2 effectsImage:(id)arg3 maskImage:(id)arg4 style:(int)arg5 ;
+(BOOL)supportsSecureCoding;
+(id)imageWithCGImage:(CGImageRef)arg1 scale:(double)arg2 orientation:(long long)arg3 ;
+(id)imageWithCGImage:(CGImageRef)arg1 ;
+(id)animatedImageWithImages:(id)arg1 duration:(double)arg2 ;
+(void)_flushCache:(id)arg1 ;
+(id)imageNamed:(id)arg1 inBundle:(id)arg2 compatibleWithTraitCollection:(id)arg3 ;
+(id)imageNamed:(id)arg1 ;
+(long long)_mirroredImageOrientationForOrientation:(long long)arg1 ;
+(UIEdgeInsets)_edgeInsetsForStylePresetNames:(id)arg1 scale:(double)arg2 ;
+(id)_animatedImageNamed:(id)arg1 inBundle:(id)arg2 compatibleWithTraitCollection:(id)arg3 duration:(double)arg4 ;
+(id)animatedResizableImageNamed:(id)arg1 capInsets:(UIEdgeInsets)arg2 resizingMode:(long long)arg3 duration:(double)arg4 ;
+(id)_animatedResizableImageNamed:(id)arg1 inBundle:(id)arg2 compatibleWithTraitCollection:(id)arg3 capInsets:(UIEdgeInsets)arg4 resizingMode:(long long)arg5 duration:(double)arg6 ;
+(void)_dropResourceReferencesForURL:(id)arg1 ;
+(BOOL)_isCGImageAlphaMask:(CGImageRef)arg1 ;
+(id)_imageNamed:(id)arg1 withTrait:(id)arg2 ;
+(id)imageWithContentsOfFile:(id)arg1 ;
+(id)imageWithData:(id)arg1 ;
+(id)imageWithData:(id)arg1 scale:(double)arg2 ;
+(id)imageWithCIImage:(id)arg1 ;
+(id)imageWithCIImage:(id)arg1 scale:(double)arg2 orientation:(long long)arg3 ;
+(id)_imageWithCGPDFPage:(CGPDFPageRef)arg1 ;
+(id)_imageWithCGPDFPage:(CGPDFPageRef)arg1 scale:(double)arg2 orientation:(long long)arg3 ;
+(id)animatedImageNamed:(id)arg1 duration:(double)arg2 ;
+(id)animatedResizableImageNamed:(id)arg1 capInsets:(UIEdgeInsets)arg2 duration:(double)arg3 ;
+(void)_clearAssetCaches;
+(id)_kitImageNamed:(id)arg1 withTrait:(id)arg2 ;
+(id)_backgroundGradientWithStartColor:(id)arg1 andEndColor:(id)arg2 ;
+(id)imageNamed:(id)arg1 inBundle:(id)arg2 ;
+(id)_defaultBackgroundGradient;
+(id)imageFromAlbumArtData:(id)arg1 height:(int)arg2 width:(int)arg3 bytesPerRow:(int)arg4 cache:(BOOL)arg5 ;
+(id)imageWithContentsOfCPBitmapFile:(id)arg1 flags:(int)arg2 ;
+(id)_deviceSpecificImageNamed:(id)arg1 ;
+(id)_deviceSpecificImageNamed:(id)arg1 inBundle:(id)arg2 ;
+(id)_noiseImage;
+(id)imageAtPath:(id)arg1 ;
+(unsigned long long)_scaleDefinedByPath:(id)arg1 ;
+(long long)_idiomDefinedByPath:(id)arg1 ;
+(int)_iconVariantForUIApplicationIconFormat:(int)arg1 idiom:(long long)arg2 scale:(double*)arg3 ;
+(int)_iconVariantForUIApplicationIconFormat:(int)arg1 scale:(double*)arg2 ;
+(id)_iconForResourceProxy:(id)arg1 variant:(int)arg2 variantsScale:(double)arg3 ;
+(id)_iconForResourceProxy:(id)arg1 variant:(int)arg2 options:(int)arg3 variantsScale:(double)arg4 ;
+(id)_iconForResourceProxy:(id)arg1 format:(int)arg2 options:(unsigned long long)arg3 ;
+(id)_applicationIconImageForBundleIdentifier:(id)arg1 format:(int)arg2 ;
+(id)_iconForResourceProxy:(id)arg1 format:(int)arg2 ;
+(id)_cachedImageForKey:(id)arg1 fromBlock:(/*^block*/id)arg2 ;
+(id)_tintedImageForSize:(CGSize)arg1 withTint:(id)arg2 maskImage:(id)arg3 effectsImage:(id)arg4 style:(int)arg5 ;
+(id)readableTypeIdentifiersForItemProvider;
+(id)_tintedImageForSize:(CGSize)arg1 withTint:(id)arg2 maskImage:(id)arg3 effectsImage:(id)arg4 style:(int)arg5 edgeInsets:(UIEdgeInsets)arg6 ;
+(id)objectWithItemProviderData:(id)arg1 typeIdentifier:(id)arg2 error:(id*)arg3 ;
+(id)writableTypeIdentifiersForItemProvider;
+(id)newObjectWithItemProviderData:(id)arg1 typeIdentifier:(id)arg2 options:(id)arg3 error:(id*)arg4 ;
+(CGSize)_legibilityImageSizeForSize:(CGSize)arg1 style:(long long)arg2 ;
-(double)scale;
-(CGSize)size;
-(void)draw3PartImageWithSliceRects:(SCD_Struct_UI13)arg1 inRect:(CGRect)arg2 operation:(int)arg3 fraction:(double)arg4 ;
-(void)draw1PartImageInRect:(CGRect)arg1 fraction:(double)arg2 operation:(int)arg3 ;
-(UITraitCollection *)traitCollection;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)patternColor;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(id)imageFlippedForRightToLeftLayoutDirection;
-(double)duration;
-(id)resizableImageWithCapInsets:(UIEdgeInsets)arg1 ;
-(CGSize)_sizeWithHairlineThickening:(BOOL)arg1 renderingEffects:(unsigned long long)arg2 forTraitCollection:(id)arg3 ;
-(UIEdgeInsets)alignmentRectInsets;
-(BOOL)_isResizable;
-(UIEdgeInsets)capInsets;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)drawInRect:(CGRect)arg1 ;
-(BOOL)_canEncodeWithName:(id)arg1 coder:(id)arg2 ;
-(void)_encodeDataWithCoder:(id)arg1 imageName:(id)arg2 ;
-(void)_encodePropertiesWithCoder:(id)arg1 ;
-(CGPDFPageRef)_CGPDFPage;
-(void)_configureImage:(id)arg1 ;
-(void)_setAlwaysStretches:(BOOL)arg1 ;
-(id)_initWithOtherImage:(id)arg1 ;
-(void)_setVectorImageCGPDFPage:(CGPDFPageRef)arg1 ;
-(CGRect)_contentStretchInPixels;
-(CGRect)_contentRectInPixels;
-(CGImageRef)CGImage;
-(long long)imageOrientation;
-(id)initWithCGImage:(CGImageRef)arg1 scale:(double)arg2 orientation:(long long)arg3 ;
-(id)imageWithAlignmentRectInsets:(UIEdgeInsets)arg1 ;
-(long long)resizingMode;
-(BOOL)_suppressesAccessibilityHairlineThickening;
-(BOOL)_isSubimage;
-(BOOL)_isTiledWhenStretchedToSize:(CGSize)arg1 ;
-(id)_resizableImageWithCapMask:(int)arg1 ;
-(NSArray *)images;
-(void)_flipImageOrientationHorizontally;
-(id)resizableImageWithCapInsets:(UIEdgeInsets)arg1 resizingMode:(long long)arg2 ;
-(void)_setAlignmentRectInsets:(UIEdgeInsets)arg1 ;
-(id)_bezeledImageWithShadowRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4 fillRed:(double)arg5 green:(double)arg6 blue:(double)arg7 alpha:(double)arg8 drawShadow:(BOOL)arg9 ;
-(id)_doubleBezeledImageWithExteriorShadowRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4 interiorShadowRed:(double)arg5 green:(double)arg6 blue:(double)arg7 alpha:(double)arg8 fillRed:(double)arg9 green:(double)arg10 blue:(double)arg11 alpha:(double)arg12 ;
-(id)_imageScaledToProportion:(double)arg1 interpolationQuality:(int)arg2 ;
-(id)_imageWithStylePresets:(id)arg1 withTintColor:(id)arg2 ;
-(void)_preheatBitmapData;
-(id)_decompressionInfo;
-(void)_decompressionComplete;
-(void)_saveDecompressedImage:(CGImageRef)arg1 ;
-(void)_decompressionFallbackImageCreation;
-(void)_setDecompressionInfo:(id)arg1 ;
-(void)_startEagerDecompression;
-(id)_initWithData:(id)arg1 immediateLoadWithMaxSize:(CGSize)arg2 scale:(double)arg3 renderingIntent:(int)arg4 ;
-(BOOL)_isDecompressing;
-(BOOL)_hasDecompressionInfo;
-(id)initWithContentsOfFile:(id)arg1 ;
-(id)initWithData:(id)arg1 ;
-(id)initWithData:(id)arg1 scale:(double)arg2 ;
-(id)initWithCGImage:(CGImageRef)arg1 ;
-(id)initWithCIImage:(id)arg1 ;
-(id)initWithCIImage:(id)arg1 scale:(double)arg2 orientation:(long long)arg3 ;
-(id)initWithContentsOfFile:(id)arg1 cache:(BOOL)arg2 ;
-(id)_initWithData:(id)arg1 preserveScale:(BOOL)arg2 cache:(BOOL)arg3 ;
-(long long)renderingMode;
-(void)_setSuppressesAccessibilityHairlineThickening:(BOOL)arg1 ;
-(void)setTraitCollection:(UITraitCollection *)arg1 ;
-(BOOL)flipsForRightToLeftLayoutDirection;
-(void)_setIsFlippedInRightToLeft;
-(CGPDFPageRef)_vectorImageCGPDFPage;
-(double)_vectorImageScale;
-(void)_setVectorImageScale:(double)arg1 ;
-(id)_vectorImageFlatColor;
-(void)_setVectorImageFlatColor:(id)arg1 ;
-(UIEdgeInsets)_vectorImagePaddingInsets;
-(void)_setVectorImagePaddingInsets:(UIEdgeInsets)arg1 ;
-(CIImage *)CIImage;
-(id)_initWithCGPDFPage:(CGPDFPageRef)arg1 scale:(double)arg2 orientation:(long long)arg3 ;
-(id)_initWithIOSurface:(IOSurfaceRef)arg1 scale:(double)arg2 orientation:(long long)arg3 ;
-(void)_configureVectorImagePropertiesForImage:(id)arg1 ;
-(BOOL)_isNamed;
-(CGSize)_sizeInPixels;
-(CGSize)_sizeInPixelsFromPDF;
-(long long)_imageOrientationConsideringRTLForUserInterfaceLayoutDirection:(long long)arg1 ;
-(id)_initWithCGPDFPage:(CGPDFPageRef)arg1 ;
-(_UIImageVectorImageSupport *)vectorImageSupport;
-(void)setVectorImageSupport:(_UIImageVectorImageSupport *)arg1 ;
-(double)_scaleFromPDF;
-(id)_cachedImageStyledWithPresets:(id)arg1 forTintColor:(id)arg2 ;
-(void)_cacheStyledImage:(id)arg1 forPresets:(id)arg2 tintColor:(id)arg3 ;
-(void)drawAtPoint:(CGPoint)arg1 blendMode:(int)arg2 alpha:(double)arg3 ;
-(void)drawInRect:(CGRect)arg1 blendMode:(int)arg2 alpha:(double)arg3 ;
-(CGSize)_CGPDFPageSize;
-(IOSurfaceRef)ioSurface;
-(id)_primitiveImageAsset;
-(UIImageAsset *)imageAsset;
-(long long)_imageOrientationConsideringRTL;
-(id)imageWithHorizontallyFlippedOrientation;
-(id)imageWithRenderingMode:(long long)arg1 ;
-(UIGraphicsImageRendererFormat *)imageRendererFormat;
-(void)drawAtPoint:(CGPoint)arg1 ;
-(void)drawAsPatternInRect:(CGRect)arg1 ;
-(BOOL)_isAlphaMask;
-(BOOL)_representsLayeredImage;
-(BOOL)_representsCIImageWhichSupportsIOSurfaceRendering;
-(void)setImageAsset:(UIImageAsset *)arg1 ;
-(id)_initWithIOSurface:(IOSurfaceRef)arg1 imageOrientation:(long long)arg2 ;
-(id)_initWithContentsOfLCRFile:(id)arg1 ;
-(id)_initWithData:(id)arg1 preserveScale:(BOOL)arg2 ;
-(id)_initWithData:(id)arg1 scale:(double)arg2 ;
-(id)initWithCGImage:(CGImageRef)arg1 imageOrientation:(long long)arg2 ;
-(id)initWithIOSurface:(IOSurfaceRef)arg1 ;
-(IOSurfaceRef)_copyIOSurface;
-(BOOL)writeToCPBitmapFile:(id)arg1 flags:(int)arg2 ;
-(id)_stretchableImageWithCapInsets:(UIEdgeInsets)arg1 ;
-(id)_resizableImageWithSubimageInsets:(UIEdgeInsets)arg1 resizeInsets:(UIEdgeInsets)arg2 ;
-(SCD_Struct_UI15)_calculateStatistics;
-(id)_flatImageWithColor:(id)arg1 ;
-(id)_imagePaddedByInsets:(UIEdgeInsets)arg1 ;
-(id)_imageThatSuppressesAccessibilityHairlineThickening;
-(id)stretchableImageWithLeftCapWidth:(long long)arg1 topCapHeight:(long long)arg2 ;
-(long long)leftCapWidth;
-(long long)topCapHeight;
-(void)compositeToPoint:(CGPoint)arg1 operation:(int)arg2 fraction:(double)arg3 ;
-(void)draw9PartImageWithSliceRects:(SCD_Struct_UI16)arg1 inRect:(CGRect)arg2 fraction:(double)arg3 ;
-(void)draw9PartImageWithSliceRects:(SCD_Struct_UI16)arg1 inRect:(CGRect)arg2 operation:(int)arg3 fraction:(double)arg4 ;
-(void)compositeToPoint:(CGPoint)arg1 fromRect:(CGRect)arg2 operation:(int)arg3 fraction:(double)arg4 ;
-(void)compositeToRect:(CGRect)arg1 fromRect:(CGRect)arg2 operation:(int)arg3 fraction:(double)arg4 ;
-(void)draw3PartImageWithSliceRects:(SCD_Struct_UI13)arg1 inRect:(CGRect)arg2 fraction:(double)arg3 ;
-(void)draw1PartImageInRect:(CGRect)arg1 fraction:(double)arg2 ;
-(CGColorRef)_tiledPatternColor;
-(CGColorRef)_patternColor;
-(id)initWithData:(id)arg1 cache:(BOOL)arg2 ;
-(CGImageRef)imageRef;
-(void)compositeToPoint:(CGPoint)arg1 operation:(int)arg2 ;
-(void)draw9PartImageWithSliceRects:(SCD_Struct_UI16)arg1 inRect:(CGRect)arg2 ;
-(void)draw3PartImageWithSliceRects:(SCD_Struct_UI13)arg1 inRect:(CGRect)arg2 ;
-(void)draw1PartImageInRect:(CGRect)arg1 ;
-(void)_setCached:(BOOL)arg1 ;
-(BOOL)_isCached;
-(void)_setNamed:(BOOL)arg1 ;
-(BOOL)_isInvisibleAndGetIsTranslucent:(BOOL*)arg1 ;
-(id)_flatImageWithWhite:(double)arg1 alpha:(double)arg2 ;
-(id)_serializedData;
-(id)_applicationIconImageForFormat:(int)arg1 precomposed:(BOOL)arg2 scale:(double)arg3 ;
-(id)_applicationIconImageForFormat:(int)arg1 precomposed:(BOOL)arg2 idiom:(long long)arg3 scale:(double)arg4 ;
-(id)_applicationIconImageForFormat:(int)arg1 precomposed:(BOOL)arg2 ;
-(id)_applyBackdropViewSettings:(id)arg1 allowImageResizing:(BOOL)arg2 ;
-(id)_applyBackdropViewSettings:(id)arg1 includeTints:(BOOL)arg2 includeBlur:(BOOL)arg3 allowImageResizing:(BOOL)arg4 ;
-(id)_applyBackdropViewStyle:(long long)arg1 includeTints:(BOOL)arg2 includeBlur:(BOOL)arg3 graphicsQuality:(long long)arg4 ;
-(id)_applyBackdropViewStyle:(long long)arg1 includeTints:(BOOL)arg2 includeBlur:(BOOL)arg3 graphicsQuality:(long long)arg4 allowImageResizing:(BOOL)arg5 ;
-(id)_applyBackdropViewSettings:(id)arg1 ;
-(id)_applyBackdropViewSettings:(id)arg1 includeTints:(BOOL)arg2 includeBlur:(BOOL)arg3 ;
-(id)_applyBackdropViewStyle:(long long)arg1 includeTints:(BOOL)arg2 includeBlur:(BOOL)arg3 ;
-(id)_subimageInRect:(CGRect)arg1 ;
-(id)_unselectedTabBarItemImageWithTintColor:(id)arg1 metrics:(long long)arg2 style:(long long)arg3 forScreenScale:(double)arg4 ;
-(id)_selectedTabBarItemImageWithTintColor:(id)arg1 metrics:(long long)arg2 style:(long long)arg3 forScreenScale:(double)arg4 ;
-(CGSize)preferredPresentationSizeForItemProvider;
-(id)initWithItemProviderData:(id)arg1 typeIdentifier:(id)arg2 error:(id*)arg3 ;
-(id)loadDataWithTypeIdentifier:(id)arg1 forItemProviderCompletionHandler:(/*^block*/id)arg2 ;
-(void)registerLoadHandlersToItemProvider:(id)arg1 ;
-(id)_tabBarItemImageWithTintColor:(id)arg1 selected:(BOOL)arg2 metrics:(long long)arg3 style:(long long)arg4 forScreenScale:(double)arg5 ;
-(id)_imageForLegibilitySettings:(id)arg1 strength:(double)arg2 ;
-(void)_drawImageForLegibilitySettings:(id)arg1 strength:(double)arg2 size:(CGSize)arg3 ;
-(id)_imageForLegibilityStyle:(long long)arg1 ;
-(void)_drawImageForLegibilityStyle:(long long)arg1 size:(CGSize)arg2 ;
-(id)_imageWithBrightnessModifiedForLegibilityStyle:(long long)arg1 ;
@end

